name: Build & Deploy to GitHub Pages

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: cd dronatrix-leaderboard && npm install --include=dev

      - name: Build Vite app
        run: cd dronatrix-leaderboard && npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dronatrix-leaderboard/dist
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
